import './global.css';
import { Container } from '@shared/components/container';
import { Space_Grotesk } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
// eslint-disable-next-line babel/new-cap
const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Welcome to axiom',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={spaceGrotesk.className} lang="en">
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
